<?php
/**
 * GetUniverseTypesTypeIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.1.dev2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetUniverseTypesTypeIdOkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetUniverseTypesTypeIdOkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetUniverseTypesTypeIdOk"
     */
    public function testGetUniverseTypesTypeIdOk()
    {

    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {

    }

    /**
     * Test attribute "graphic_id"
     */
    public function testPropertyGraphicId()
    {

    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {

    }

    /**
     * Test attribute "icon_id"
     */
    public function testPropertyIconId()
    {

    }

    /**
     * Test attribute "type_description"
     */
    public function testPropertyTypeDescription()
    {

    }

    /**
     * Test attribute "type_name"
     */
    public function testPropertyTypeName()
    {

    }

}
