<?php
/**
 * UniverseApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.3.1.dev2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UniverseApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UniverseApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getUniverseStationsStationId
     *
     * Get station information.
     *
     */
    public function testGetUniverseStationsStationId()
    {

    }

    /**
     * Test case for getUniverseStructures
     *
     * List all public structures.
     *
     */
    public function testGetUniverseStructures()
    {

    }

    /**
     * Test case for getUniverseStructuresStructureId
     *
     * Get structure information.
     *
     */
    public function testGetUniverseStructuresStructureId()
    {

    }

    /**
     * Test case for getUniverseSystemsSystemId
     *
     * Get solar system information.
     *
     */
    public function testGetUniverseSystemsSystemId()
    {

    }

    /**
     * Test case for getUniverseTypesTypeId
     *
     * Get type information.
     *
     */
    public function testGetUniverseTypesTypeId()
    {

    }

    /**
     * Test case for postUniverseNames
     *
     * Get names and categories for a set of ID's.
     *
     */
    public function testPostUniverseNames()
    {

    }

}
